### ISSUE TITLE
cofight Server missing

### ISSUE THREAD

**Issue by dslhias** [CoFight-19/cofight-android#1]
Hello,
is there a basic server code ?
I set up a http-server that replies "1" to the eight digit phone-number.
But what about the activation code ?
grateful for any help
mateng

**Comment by netcyrax** [comment]
Hello and thanks for the interest In our project!

We have a repository for the server-side: https://github.com/CoFight-19/cofight-cfml
The code has not yet been uploaded. You can subscribe to the repo to get notified.
